platform :ios, '9.0'

target 'FMBaseKitExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'FMBaseKit', :path => './../'

end
